import type { AgentMessage, ThinkingLevel } from "@earendil-works/pi-agent-core";
import type { Model } from "@earendil-works/pi-ai";

export interface SessionUsage {
	input: number;
	output: number;
	cacheRead: number;
	cacheWrite: number;
	totalTokens: number;
	cost: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
		total: number;
	};
}

export interface SessionMetadata {
	id: string;
	title: string;
	parentSessionId?: string | null;
	forkedAt?: string;
	createdAt: string;
	lastModified: string;
	messageCount: number;
	usage: SessionUsage;
	thinkingLevel: ThinkingLevel;
	preview: string;
	/** Whether the title was generated by AI (blocks manual rename until true). */
	aiGeneratedTitle?: boolean;
}

export interface SessionData {
	id: string;
	title: string;
	parentSessionId?: string | null;
	forkedAt?: string;
	model: Model<any>;
	thinkingLevel: ThinkingLevel;
	messages: AgentMessage[];
	createdAt: string;
	lastModified: string;
	/** Mirrors metadata.aiGeneratedTitle for round-trip persistence. */
	aiGeneratedTitle?: boolean;
}
