import type { AgentMessage, ThinkingLevel } from "@earendil-works/pi-agent-core";
import type { Model } from "@earendil-works/pi-ai";

export interface SessionUsage {
	input: number;
	output: number;
	cacheRead: number;
	cacheWrite: number;
	totalTokens: number;
	cost: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
		total: number;
	};
}

export interface SessionMetadata {
	id: string;
	title: string;
	parentSessionId?: string | null;
	forkedAt?: string;
	createdAt: string;
	lastModified: string;
	messageCount: number;
	usage: SessionUsage;
	thinkingLevel: ThinkingLevel;
	modelProvider?: string;
	modelId?: string;
	modelName?: string;
	modelApi?: string;
	modelReasoning?: boolean;
	preview: string;
	/** Full plain-text message corpus for local session search. */
	searchText?: string;
	/** Whether the title was generated by AI (blocks manual rename until true). */
	aiGeneratedTitle?: boolean;
	/** Internal counterfactual generated for an explicit learner comparison. */
	generatedAlternative?: boolean;
	/** Keep unselected counterfactuals out of the normal session browser. */
	hiddenAlternative?: boolean;
	alternativeForMessageTimestamp?: number;
	responsePreference?: "original" | "alternative" | "skipped";
}

export interface SessionData {
	id: string;
	title: string;
	parentSessionId?: string | null;
	forkedAt?: string;
	model: Model<any>;
	thinkingLevel: ThinkingLevel;
	messages: AgentMessage[];
	createdAt: string;
	lastModified: string;
	/** Mirrors metadata.aiGeneratedTitle for round-trip persistence. */
	aiGeneratedTitle?: boolean;
	generatedAlternative?: boolean;
	hiddenAlternative?: boolean;
	alternativeForMessageTimestamp?: number;
	responsePreference?: "original" | "alternative" | "skipped";
}
