import { mkdir, cp } from "node:fs/promises";
import { join } from "node:path";
const root = import.meta.dir;
type Section = {heading:string; paragraphs?:string[]; bullets?:string[]; code?:string; language?:string; links?:{label:string;href:string}[]};
type Page = {slug:string;title:string;description:string;group:string;sections:Section[]};
const pages:Page[] = [];
for (const file of ["core.json","platform.json"]) pages.push(...await Bun.file(join(root,"content",file)).json());
const esc=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const id=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const groups=[...new Set(pages.map(p=>p.group))];
const nav=(slug:string)=>groups.map(g=>`<div class="nav-group"><p>${esc(g)}</p>${pages.filter(p=>p.group===g).map(p=>`<a href="/${p.slug}/" ${p.slug===slug?'aria-current="page"':''}>${esc(p.title)}</a>`).join("")}</div>`).join("");
function shell(title:string,desc:string,body:string,slug="",toc="") {return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Keating developers</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="https://dev.keating.help/${slug?slug+"/":""}"><meta property="og:title" content="${esc(title)} · Keating developers"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="website"><link rel="icon" href="/assets/keatingbot.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/"><img src="/assets/keatingbot.png" alt="" width="42" height="42"><span>keating<span class="brand-sub">/ developers</span></span></a><nav aria-label="External links"><a href="https://github.com/Diogenesoftoronto/keating">Source ↗</a><a class="open" href="https://keating.help/chat">Open Keating ↗</a></nav></header><div class="layout"><aside class="sidebar"><details class="mobile-nav"><summary>Browse documentation</summary>${nav(slug)}</details><nav class="desktop-nav" aria-label="Documentation"><a class="overview" href="/" ${!slug?'aria-current="page"':''}>Overview</a>${nav(slug)}</nav></aside><main id="main"><div class="search"><label for="search">Find something in Keating</label><input id="search" type="search" placeholder="Search guides, tools, architecture…" autocomplete="off"><div id="results" hidden role="region" aria-label="Search results" aria-live="polite"></div></div>${body}<footer><p>Keating is built to help people think for themselves.</p><a href="https://keating.help">Product</a> · <a href="https://github.com/Diogenesoftoronto/keating/blob/main/LICENSE">License</a> · <a href="https://github.com/Diogenesoftoronto/keating/issues">Report a docs issue ↗</a></footer></main><aside class="toc" aria-label="On this page">${toc}</aside></div></body></html>`;}
await mkdir(join(root,"public/assets"),{recursive:true});
await cp(join(root,"assets"),join(root,"public/assets"),{recursive:true});
const home=`<section class="hero"><p class="eyebrow">THE KEATING DEVELOPER HANDBOOK</p><h1>A model can give an answer.<br><em>Teaching takes a system.</em></h1><p class="lead">When the answer arrives before the understanding, something is missing. Keating brings plans, practice, memory, and verification around the model—so the learner can do the thinking.</p><div class="actions"><a class="button" href="/getting-started/">Build with Keating →</a><a href="/architecture/">Understand the architecture ↗</a></div><div class="system"><div><span>01 / INTENT</span><strong>What do you want to understand?</strong></div><b aria-hidden="true">→</b><div><span>02 / PRACTICE</span><strong>Plan. Try. Explain. Revise.</strong></div><b aria-hidden="true">→</b><div><span>03 / EVIDENCE</span><strong>Show what you can do.</strong></div></div></section><section><p class="eyebrow">START WITH YOUR QUESTION</p><h2>Find your way into the system.</h2><div class="paths"><a href="/getting-started/"><span>01 / DEVELOP</span><h3>Run it yourself.</h3><p>Set up a workspace, start the CLI, and find the web development workflow.</p><b>Get started →</b></a><a href="/extending-keating/"><span>02 / EXTEND</span><h3>Shape how it teaches.</h3><p>Work with prompts, skills, deterministic tools, and shared learner interactions.</p><b>Extension guide →</b></a><a href="/evaluation-and-evolution/"><span>03 / INVESTIGATE</span><h3>Ask what improves.</h3><p>Explore teaching evaluations, policy evolution, and the limits of synthetic evidence.</p><b>Research guide →</b></a></div></section><section class="directory"><p class="eyebrow">THE WHOLE PICTURE</p><h2>From the learner to the runtime.</h2>${groups.map(g=>`<h3>${esc(g)}</h3><div class="guide-list">${pages.filter(p=>p.group===g).map(p=>`<a href="/${p.slug}/"><strong>${esc(p.title)} <span>↗</span></strong><p>${esc(p.description)}</p></a>`).join("")}</div>`).join("")}</section><section class="note"><h2>Built in the open. Read with the source.</h2><p>These guides explain the repository’s design and implementation. Each topic links to its source; client support and hosted availability can differ. Evaluation results are not proof of human learning gains.</p><a href="/contributing/">Contribute to Keating →</a></section>`;
await Bun.write(join(root,"public/index.html"),shell("Build for understanding","Architecture, guides, and reference for Keating, the teaching system built around the learner.",home));
for (const p of pages) {
 if(!/^[a-z0-9-]+$/.test(p.slug)) throw Error("Invalid slug");
 const body=`<article><p class="eyebrow">${esc(p.group)} / HANDBOOK</p><h1>${esc(p.title)}</h1><p class="lead">${esc(p.description)}</p>${p.sections.map(s=>`<section id="${id(s.heading)}"><h2><a class="heading-anchor" href="#${id(s.heading)}">${esc(s.heading)}</a></h2>${(s.paragraphs||[]).map(t=>`<p>${esc(t)}</p>`).join("")}${s.bullets?`<ul>${s.bullets.map(t=>`<li>${esc(t)}</li>`).join("")}</ul>`:""}${s.code?`<div class="code-label">${esc(s.language||"Terminal")}</div><pre><code>${esc(s.code)}</code></pre>`:""}${s.links?`<div class="source-links">${s.links.map(l=>`<a href="${esc(l.href)}">${esc(l.label)} ↗</a>`).join("")}</div>`:""}</section>`).join("")}<div class="article-end"><a href="/">← All documentation</a><a href="https://github.com/Diogenesoftoronto/keating/issues">Suggest a correction ↗</a></div></article>`;
 await mkdir(join(root,"public",p.slug),{recursive:true});
 await Bun.write(join(root,"public",p.slug,"index.html"),shell(p.title,p.description,body,p.slug,`<p>ON THIS PAGE</p>${p.sections.map(s=>`<a href="#${id(s.heading)}">${esc(s.heading)}</a>`).join("")}`));
}
await Bun.write(join(root,"public/search.json"),JSON.stringify(pages.map(p=>({title:p.title,description:p.description,url:`/${p.slug}/`,text:p.sections.map(s=>[s.heading,...s.paragraphs||[],...s.bullets||[],s.code||""].join(" ")).join(" ")}))));
await Bun.write(join(root,"public/404.html"),shell("Page not found","Find your way back to the Keating developer handbook.",`<h1>This page isn't here.</h1><p>Search the handbook above, or return to the overview.</p><a class="button" href="/">Back to the handbook →</a>`));
await Bun.write(join(root,"public/robots.txt"),"User-agent: *\nAllow: /\nSitemap: https://dev.keating.help/sitemap.xml\n");
await Bun.write(join(root,"public/sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${["",...pages.map(p=>p.slug+"/")].map(s=>`<url><loc>https://dev.keating.help/${s}</loc></url>`).join("")}</urlset>`);
console.log(`Built ${pages.length+1} pages and search index.`);
