import { writeFile } from "node:fs/promises";
import { summarize, type Receipt } from "./benchmark.js";
import { digest, type Trial } from "./cases.js";

const pct = (n: number | null) => n === null ? "—" : `${(100 * n).toFixed(1)}%`;
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]!));
export function reportData(trials: readonly Trial[], receipts: readonly Receipt[]) {
  const summary = summarize(trials, receipts);
  const lookup = new Map(trials.map(row => [row.id, row]));
  const disagreements = summary.disagreements.map(row => {
    const question = lookup.get(row.trialId)?.request.questions[row.question];
    const hide = (value: unknown) => typeof value === "string" && question?.type === "choice" && (row.question === "evidence" || value.length > 80) ? `option-sha256:${digest(value).slice(0, 16)}` : value;
    return { ...row, value: hide(row.value), expected: hide(row.expected) };
  });
  return { ...summary, disagreements, interpretationWarnings: trials.some(row => row.caseId.includes("openui_valid")) ? ["Legacy openui_valid requests omitted the complete UI schema/compiler contract. Their unchanged labels measure host agreement only, not primary model accuracy. Abstention can be reasonable. Future plans exclude these underspecified diagnostics."] : [], trials: trials.map(({ id, family, split, kind, labelSource, placement, path, targetFill, cueRetained, turnsDropped, before, after, requestSha256 }) => ({ id, family, split, kind, labelSource, placement, path, targetFill, cueRetained, turnsDropped, before, after, requestSha256 })), errors: receipts.filter(row => row.outcome.status === "error").map(row => ({ trialId: row.trialId, provider: row.providerId, status: row.status, reason: row.outcome.status === "error" ? row.outcome.error : "" })) };
}
export function markdownReport(trials: readonly Trial[], receipts: readonly Receipt[], title = "Judgement under context pressure") {
  const data = reportData(trials, receipts);
  const native = trials.some(row => row.stage);
  const heading = native ? "Keating production judgement batches" : title;
  const budgets = [...new Set(trials.map(row => row.before.budgetTokens).filter(value => value !== null))].join(", ");
  const rows = data.cells.map(row => `| ${row.key.replaceAll("|", " · ")} | ${row.correct}/${row.labelled} | ${pct(row.exactLabelledBatchAccuracy)} | ${row.labelled}/${row.requestedQuestions} | ${pct(row.responseCoverage)} | ${pct(row.balancedAccuracy)} | ${row.positive}/${row.negative} | ${pct(row.fullContextAgreement)} |`);
  return `# ${heading}\n\nThis is a verifier pilot, not a measure of human learning or a scaling-law result. ${data.independentFamilies} task families appear in this run; window variants and repeated responses are correlated. Authored answer keys, executable rollout gates, and reference-model opinions have different evidential status.\n\nA perfect score on easy controls is a ceiling signal. Harder tasks belong in a new frozen version; never alter labels, omit failures, or choose a release because it produces a desired model ranking. Model size is a hypothesis, not the answer key.\n\n${native ? "These are authored lesson episodes using the exact production planning, draft-review and grading requests. Full batches are sent; only the explicitly justified gold assertions are scored. Unlabelled questions have no accuracy claim. Batch accuracy requires every labelled assertion to match. Native conversation lengths are retained, without artificial padding.\n\n" : ""}The table keeps every scheduled label in its denominator, including provider errors and undispatched requests. “Visible” labels become insufficient_context when the sole authored cue is evicted; agreement with the original full-context label measures information loss separately. Boolean gate accuracy is paired with positive/negative counts and balanced accuracy. Brier scores are available only for actual probability outputs.\n\n| Model · task · label source · split · placement · path · fill · stage / probe | Label match | Entire labelled batch | Labelled / requested | Response coverage | Balanced boolean accuracy | True / false gold | Full-context agreement |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n${rows.join("\n")}\n\n${data.interpretationWarnings.join(" ")}

${data.errors.length} scheduled requests failed or were not dispatched. See summary.json and report.html for exact status codes, cell filters, latency, baselines and disagreement IDs. Raw private requests and responses remain in the local plan and receipt files and are deliberately omitted from this report.\n\nThe current window removes old complete conversation turns at 80% of the estimated ${budgets || "unavailable"}-token state-plus-longest-question budget, aiming for 65%. Pinned lesson state and submissions remain. These are host estimates, not the provider tokenizer or proof of the provider's effective context limit.\n`;
}
export function htmlReport(trials: readonly Trial[], receipts: readonly Receipt[]) {
  const data = reportData(trials, receipts);
  const heading = trials.some(row => row.stage) ? "Keating production judgement batches" : "Judgement under context pressure";
  const payload = JSON.stringify(data).replaceAll("<", "\\u003c");
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${heading}</title><style>
:root{font-family:system-ui,sans-serif;color:#242b2b;background:#f6f3ed;color-scheme:light}body{max-width:1300px;margin:auto;padding:32px 24px}h1{font-family:Georgia,serif;font-weight:400;font-size:clamp(32px,5vw,58px);margin-bottom:12px}p{max-width:880px;line-height:1.6}.note{border-left:3px solid #947342;padding-left:16px}label{display:inline-flex;gap:8px;align-items:center;margin:8px 16px 16px 0}select{padding:8px;border:1px solid #999;background:#fff;border-radius:4px;max-width:230px}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #d5d5cc;white-space:nowrap}th{background:#e9e9df}meter{width:110px}summary{cursor:pointer;padding:16px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}button{padding:10px 14px;background:#24554e;color:white;border:0;border-radius:4px;cursor:pointer}#count{font-variant-numeric:tabular-nums}.legend{color:#52605a;font-size:14px}td.bad{color:#973b30}
</style><h1>${heading}</h1><p>Can a verifier find the evidence, respect its limits, and identify a faulty teaching response?</p><p class="note">${escapeHtml(data.notice)} ${escapeHtml(data.interpretationWarnings.join(" "))} Full production batches may include unlabelled outputs. Only explicit gold assertions count toward accuracy; label coverage shows that boundary. A perfect easy-control score is a ceiling signal. Model-size ordering is a hypothesis to test, never a required result.</p><div id="filters"></div><p id="count" aria-live="polite"></p><div class="scroll"><table><thead><tr><th>Model</th><th>Task / labels</th><th>Split</th><th>Evidence</th><th>Window</th><th>Target fill</th><th>Label match</th><th>Entire labelled batch</th><th>Labelled / requested</th><th>Response coverage</th><th>Full-context agreement</th><th>Balanced boolean accuracy</th><th>True / false gold</th><th>Brier ↓</th><th>Median ms</th></tr></thead><tbody id="cells"></tbody></table></div><p class="legend">Label accuracy includes all planned gold assertions; unlabelled outputs are never counted as correct. Entire-batch accuracy requires all its labelled judgements to match. Missing responses never earn abstention credit. Full-context agreement uses the original answer before any eviction. Balanced boolean accuracy averages true-label and false-label recall; true denotes a violation only for adherence checks. — means a class is absent. Empty probability metrics mean unavailable. Fill uses the host estimator. Variants are not independent samples.</p><details><summary>Window trace: evidence survival and retained state</summary><div class="scroll"><table><thead><tr><th>Trial</th><th>Before → after tokens</th><th>Turns dropped</th><th>Evidence remains</th><th>Plan / submission pinned</th></tr></thead><tbody id="traces"></tbody></table></div></details><details><summary>Disagreement IDs and provider failures</summary><pre id="details"></pre></details><button id="download">Download aggregate results</button><script type="application/json" id="data">${payload}</script><script>
const data=JSON.parse(document.getElementById('data').textContent), rows=data.cells.map(r=>({...r,axes:r.key.split('|')}));
const dimensions=[['Model',0],['Task',1],['Labels',2],['Split',3],['Evidence',4],['Window',5],['Stage / probe',7]], filters=[];
for(const [label,index] of dimensions){const l=document.createElement('label');l.append(label);const s=document.createElement('select');s.setAttribute('aria-label',label);for(const v of ['All',...new Set(rows.map(r=>r.axes[index]))]){const o=document.createElement('option');o.value=v;o.textContent=v;s.append(o)}l.append(s);document.getElementById('filters').append(l);filters.push([s,index]);s.addEventListener('change',render)}
const pct=n=>n==null?'—':(n*100).toFixed(1)+'%';
function render(){const selected=rows.filter(r=>filters.every(([s,i])=>s.value==='All'||s.value===r.axes[i]));const body=document.getElementById('cells');body.replaceChildren();for(const r of selected){const tr=document.createElement('tr');const a=r.axes;for(const v of [a[0],a[1]+' / '+a[7]+' / '+a[2],a[3],a[4],a[5],a[6]==='native'?'native':pct(Number(a[6])),r.correct+'/'+r.labelled+' ('+pct(r.accuracyAllPlannedLabels)+')',pct(r.exactLabelledBatchAccuracy),r.labelled+'/'+r.requestedQuestions,pct(r.responseCoverage),pct(r.fullContextAgreement),pct(r.balancedAccuracy),r.positive+' / '+r.negative,r.brier==null?'—':r.brier.toFixed(3),r.medianMs==null?'—':Math.round(r.medianMs)]){const td=document.createElement('td');td.textContent=v;tr.append(td)}body.append(tr)}document.getElementById('count').textContent=selected.length+' cells · '+data.independentFamilies+' task families in the complete run';}
for(const r of data.trials){const tr=document.createElement('tr');for(const v of [r.id,r.before.estimatedStateQuestionTokens+' → '+r.after.estimatedStateQuestionTokens,r.turnsDropped,r.cueRetained?'yes':'no',(r.after.pinned.plan?'yes':'no')+' / '+(r.after.pinned.pendingSubmissions?'yes':'no')]){const td=document.createElement('td');td.textContent=v;tr.append(td)}document.getElementById('traces').append(tr)}
document.getElementById('details').textContent=JSON.stringify({disagreements:data.disagreements,errors:data.errors,referenceAgreement:data.referenceAgreement},null,2);document.getElementById('download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='judgement-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};render();
</script></html>`;
}
export async function writeReports(directory: string, trials: readonly Trial[], receipts: readonly Receipt[]) {
  await writeFile(`${directory}/summary.json`, JSON.stringify(reportData(trials, receipts), null, 2), { mode: 0o600 });
  await writeFile(`${directory}/report.md`, markdownReport(trials, receipts), { mode: 0o600 });
  await writeFile(`${directory}/report.html`, htmlReport(trials, receipts), { mode: 0o600 });
}
