export function webHelpText(): string {
  return [
    "Keating Web — browser UI and agent execution runtimes",
    "",
    "Usage:",
    "  keating web [port] [runtime mode] [options]",
    "  keating web --help",
    "",
    "Runtime modes (choose one):",
    "  --browser-only-agent   Run the browser-first experience (default). NodePod can be",
    "                         started from the runtime panel when an isolated sandbox is wanted.",
    "  --host                 Run commands directly on this trusted machine (not a sandbox).",
    "  --remote               Use an external sandbox or compatible runtime service.",
    "  --cloud                Use the hosted Keating runtime service.",
    "",
    "Common options:",
    "  --root=PATH            Project directory exposed to the selected runtime (default: $CWD).",
    "  --no-ignore            Include files ignored by .gitignore/.ignore when browsing the project.",
    "  --allow-local-exec     Allow trusted localhost tools to run commands and change files under --root.",
    "",
    "Remote runtime options:",
    "  --remote-provider=NAME External provider label or adapter name.",
    "  --remote-endpoint=URL  Base URL of an external runtime service.",
    "  --remote-region=NAME   Provider region hint.",
    "  --remote-snapshot=ID   Provider snapshot/image hint.",
    "  --remote-cpu=VALUE     Requested CPU hint.",
    "  --remote-memory=VALUE  Requested memory hint.",
    "  --remote-disk=VALUE    Requested disk hint.",
    "  --cloud-endpoint=URL   Override the hosted Keating service URL.",
    "",
    "Examples:",
    "  # Browser-first mode; choose or start NodePod from the runtime panel",
    "  keating web 3000 --browser-only-agent --root=/srv/my-project",
    "",
    "  # Run agent commands directly on this trusted host (outside a sandbox)",
    "  keating web 3000 --host --allow-local-exec --root=/srv/my-project",
    "",
    "  # Use any compatible external sandbox/runtime service",
    "  keating web 3000 --remote --remote-provider=my-sandbox \\",
    "    --remote-endpoint=https://sandbox.example.com --root=/workspace",
    "",
    "  # Use Keating Cloud",
    "  keating web 3000 --cloud --cloud-endpoint=https://keating.help",
    "",
    "External runtime contract:",
    "  Keating sends POST requests to <endpoint>/api/agent-runtime/execute with JSON:",
    "    { \"operation\": \"shell.exec\", \"payload\": { ... } }",
    "  A compatible service can implement shell.exec, fs.list, fs.read, fs.write,",
    "  fs.edit, source.diff, and runtime.ping as needed.",
    "",
    "Environment variables:",
    "  KEATING_WEB_REMOTE_AUTH_TOKEN  Server-only bearer token sent to the external runtime.",
    "  KEATING_WEB_REMOTE_PROVIDER    Default for --remote-provider.",
    "  KEATING_WEB_REMOTE_ENDPOINT    Default for --remote-endpoint.",
    "  KEATING_WEB_CLOUD_ENDPOINT     Default for --cloud-endpoint.",
    "",
    "Trust and safety:",
    "  Host mode is intentionally not a sandbox. It is restricted to loopback clients and",
    "  the configured project root, but commands run with the Keating server process's host",
    "  permissions. Only enable it on a machine and project you trust.",
    "  External runtimes keep credentials server-side; never put the auth token in browser code."
  ].join("\n");
}
