= Discussion

== How well does Keating fulfill its promise?

The strongest present claim is architectural: Keating implements a broad teaching environment and an auditable procedure for changing some of its teaching instructions. Its tools can organize instruction, elicit work, grade specified answers, and retain evidence across sessions. The new loop also makes a proposed revision execute before it can be accepted. These are concrete capabilities. They support evaluating Keating as a serious teaching system, but do not support a numerical rating of educational effectiveness from repository inspection alone.

The evidence remains weakest where the product promise is most consequential: whether learners gain durable, transferable understanding while relying less on the tutor. The archive contains model-role transcripts, and the legacy simulator directly maps favored policy controls to simulated outcomes. Neither supplies an estimate for that promise. A useful assessment therefore has three parts: implementation and traceability are demonstrable; teaching behavior is now testable under a fixed protocol but lacks new live-provider results here; human learning efficacy remains unmeasured. Combining these into one readiness score would conceal the missing evidence.

The old optimizer results sharpen that assessment. The frozen policy wins all 200 aggregate comparisons inside the algebraic surface, while standardized reevaluation of 30 later selections yields 15 regressions and a mean delta near zero. Those findings are compatible: a favorable point on a known score surface does not validate the selection procedure or its educational interpretation. The redesign removes co-evolved scoring weights and retrospective policy bonuses from the activation decision. It then tests a changed procedure through actual tutor execution rather than asking the same fixed observations to justify a counterfactual improvement.

== What self-evolution means in this implementation

Keating's current unit of adaptation is a bounded teaching skill. The system retains raw observations and evidence-linked hypotheses, proposes one change, tests it, and advances an active revision only when both gates pass. Failed candidates can still contribute to later reflection. This makes the accumulated history useful independently of whether the latest edit succeeds.

This design does not yet establish that the history causes better future proposals. A hypothesis ledger can accumulate mistaken explanations, repeated strategies, or domain-specific rules that do not generalize. Its relationship to raw evidence makes those errors inspectable, not impossible. The ledger is also smaller in scope than a maintained knowledge base with contradiction resolution, retrieval, and consolidation. No autonomous code rewrite, model-weight training, cross-account learning, or indefinite holdout recycling is part of the new activation loop.

The key practical constraint is independent evidence supply. A consumed release pack must be replaced by new tasks, including after a rejected candidate. That slows iteration but prevents repeated consultation of the same release evidence through the ordinary API. An unattended service would need a controlled task-authoring process, a separate evaluator owner, explicit resource budgets, and policies for drift and evidence renewal. These are future operational components, not features established by the present implementation.

== A stronger benchmarking program

The next behavior study should freeze cases and judging prompts before search, calibrate judgments against blinded human ratings, and evaluate the same underlying tutor model under four conditions: base instructions, a fixed expert-authored skill, proposals based only on the latest traces, and proposals with the accumulated hypothesis ledger. Equalize permitted tools and budgets. Use several independently authored packs and record all attempted proposals, errors, critical failures, family-level differences, latency, token usage, and cost. This would test whether evolution improves behavior and whether retained hypotheses add value beyond another attempt at prompting.

Adversarial cases should challenge the intended mechanism directly: generic question spam, inappropriate refusal to explain, copying answers instead of eliciting work, needless tool calls, false claims of verification, and instructions in a tutor output that try to influence its judge. The existing cases already vary hint and explanation requests, while the local tests exercise missing and altered evidence. A dedicated adversarial behavior study has not been completed. Matching actor and judge models, repeating evaluation in a fixed order, and reusing authoring conventions can all produce correlated errors even with separate splits.

A human study should follow with randomized assignment to a frozen Keating revision and a strong tutor baseline using comparable model access and instructional time. Prespecify the primary outcome, analyze all assigned participants with disclosed missingness, and separate assisted practice from unaided testing. Include baseline knowledge, immediate performance, delayed recall, transfer to new problems, and an explanation that requires learners to reconstruct the concept without the tutor. The new assessment records help implement that workflow, but their tiny fixed banks require expansion, equivalent-form work, and independent grading of richer responses before they can support such a study. A priori sample-size planning must use a stated meaningful effect and variance assumptions; the 18 synthetic cases are not that calculation.

The educational objective should remain independent reconstruction and useful transfer, with correctness and learner requests as constraints. Engagement, conversational fluency, session length, and the frequency of retrieval prompts can diagnose experience, but should not become interchangeable substitutes for learning. Spaced review remains motivated by distributed-practice research @cepeda2006; Keating's scheduling heuristic is not calibrated or evaluated by this paper.
