= Discussion

The evidence supports three main claims.

First, Keating is usefully understood as a *teaching metaharness*. Its systems contribution is not simply a conversational interface, but an explicit control architecture around the exchange: persistent learner evidence, inspectable artifacts, policy parameters, evaluation paths, and reversible improvement procedures.

Second, the archival model traces yield meaningful failure analysis. High clarity can coexist with weak demonstrated mastery, introspective tasks were harder than formal technical tasks in this small archive, and student-role contamination provides a concrete example of fluent output without learner ownership.

Third, the frozen policy is robust inside the deterministic score model, but the optimizer result does not demonstrate reliable scalar improvement. The policy beats the default on every aggregate suite seed sampled. By contrast, when independently selected derivative-focused policies are reevaluated against the default on the same seed and fixed objective weights, only 11 improve, four tie, and 15 regress; the mean delta is -0.014. That distinction separates evidence for one frozen policy from evidence about the search procedure that produced later candidates.

The standardized regressions expose a design issue in the current PROSPER-style selection path. Search co-evolves policy coordinates and objective weights, evaluates candidates on different seeds, and then chooses across scalar score, counterfactual robustness, mastery, transfer, low confusion, and evidence readiness. In a synthetic-only run, counterfactual and evidence-readiness signals are absent or uninformative, and a winner under its search conditions can underperform under a common objective and seed. Production reduces this risk by requiring at least five real learner outcomes before evolution and by rolling back sufficiently large post-evolution regressions in the transactional auto-improvement loop. Those controls are implemented safeguards; they are not evidence that reward hacking or harmful policy drift has been eliminated.

The paper does *not* claim that Keating has been proven superior for human learners. The archive contains model-generated learner roles, not human participants; its labels are small, unblinded, and lack scorer provenance or inter-rater reliability. The synthetic benchmark is implemented and reproducible, but it remains a model of pedagogy rather than pedagogy itself. Nor do these experiments validate newer product capabilities such as live multimodal teaching, browser-local models, courses, collaboration, or spaced-review scheduling.

The next decisive study is a preregistered randomized comparison between Keating and at least one strong AI tutor baseline, with human participants, blinded rubric scoring, delayed retention tests, and explicit transfer tasks. In parallel, the benchmark should gain hidden holdout topics and coefficients, adversarial tests for degenerate strategies, and external transcript review. The goal is not merely to make policy search score better, but to make the link between the score and independent learner reconstruction harder to fake.
