= Introduction

One-to-one tutoring and intelligent tutoring systems provide important evidence that instructional support can improve learning @bloom1984; @ma2014. Recent work includes a randomized study of a structured generative-AI tutor @kestin2025 and a deployed generative teaching assistant examined through use and learner perception @thesen2025. Such findings do not validate every system called an AI tutor. The instructional procedure, learner population, comparison condition, and outcome measure matter.

Keating's promise is to help learners reconstruct ideas and use them independently. Its teaching design emphasizes diagnosis, self-explanation, retrieval, and transfer, drawing on established research @chi1989; @rittlejohnson2017; @roediger2006. Fluent explanations alone are an inadequate success measure: cognitive offloading can change what a learner does and subsequently remembers @risko2016; @burnett2026. Conversely, requiring questions or retrieval in every situation can be unhelpful when a learner needs an explicit explanation. An agency-preserving tutor must respond to the learner's actual need, not maximize the visible frequency of a preferred teaching technique.

This paper describes Keating as a *teaching metaharness*: a controller around the teaching exchange that maintains artifacts, learner evidence, and rules for changing the tutor. Terminal and browser interfaces support live teaching alongside plans, maps, quizzes, decks, verification, and other activities. Their breadth makes the central evaluation question sharper: does a change improve what the tutor does, and does that improvement subsequently help a learner? Interface coverage, artifact generation, satisfaction, and delayed unaided performance answer different parts of that question.

An audit of the earlier improvement path identified three measurement problems. A deterministic simulator could reward changes to its own policy coordinates without executing changed teaching. Candidate-dependent weights made search scores difficult to compare. Historical learner feedback could describe an old interaction but could not supply the learner's counterfactual response to a new tutor. The historical results retained here illustrate these problems; they do not establish the efficacy of the replacement.

The revised system separates raw executions, accumulated hypotheses, and deployable skills. This organization is informed by WikiSkill's distinction between immutable experience, persistent knowledge, and procedural skills @tang2026wikiskill. Keating implements a smaller hypothesis ledger and one reflective proposal per invocation; it does not reproduce WikiSkill's full wiki-maintenance system or claim its reported task-performance gains. Related work on harness optimization provides the broader systems context @lee2026metaharness; @zhang2026hyperagents.

The contributions are: (1) an implemented procedure for evaluating and activating teaching skill revisions against fixed behavior criteria; (2) explicit measurement boundaries between observed assessments, proxies, synthetic continuations, and human learning outcomes; and (3) a reproducible analysis connecting the earlier system's failure modes to the new design. Agency preservation is the instructional objective, not an empirically established property of this release.
