= Introduction

One-to-one tutoring remains one of the strongest known educational interventions @bloom1984, and intelligent tutoring systems improve learning outcomes on average across domains @ma2014. Recent work includes both a randomized trial of a structured generative-AI tutor @kestin2025 and a deployed generative teaching assistant studied through use and learner perception @thesen2025. But tutoring quality cannot be judged only by whether the learner receives an explanation. Learning requires active reconstruction, self-explanation, retrieval, and transfer, whereas AI systems make it unusually easy for the learner to accept a polished account instead of generating one @chi1989; @rittlejohnson2017; @roediger2006. This is exactly the terrain where cognitive offloading becomes a serious educational risk @risko2016; @burnett2026.

Keating is built for that failure mode. The central idea is simple: if conventional AI tutors are mostly *chatbots that teach*, Keating is a *metaharness that governs teaching*. A chatbot is primarily an interaction policy at the level of the next response. Keating adds a control level above that response policy. It coordinates plans, maps, visual and interactive artifacts, verification checks, quizzes, flashcards, persistent learner state, prompt evolution, benchmark traces, and policy search across terminal, browser, and live multimodal teaching surfaces. The live exchange is therefore only one component of a larger pedagogical system. The controller also extends across time: it records lesson cadence, quiz and review evidence, and topic revisit urgency, using a simple retention-decay heuristic to propose spaced review. The educational motivation for spacing is well established @cepeda2006, but Keating's particular scheduling heuristic is not evaluated in this paper.

That distinction matters both scientifically and technically. For readers from learning science, the key claim is that the system is organized around diagnosis, retrieval, self-explanation, and transfer rather than answer delivery. For readers from machine learning and systems, the object being optimized is not merely a prompt or transcript but an *instructional environment* with explicit state, artifacts, objective functions, mutation operators, and acceptance boundaries. Recent systems work has begun to optimize harnesses and editable meta-level agents outside education @lee2026metaharness; @zhang2026hyperagents. Keating applies that outer-loop framing to teaching while keeping provider-backed interaction, deterministic analysis, and real-learner evidence as distinct epistemic layers.

We make three contributions:

1. We formalize Keating as a teaching metaharness with explicit interaction, evidence, artifact, governance, and improvement layers.
2. We provide a mathematical and operational account of the deterministic fallback harness and the MAP-Elites/PROSPER policy-search path used in the study.
3. We present a versioned analysis stack that separates archival model-trace evaluation, internal synthetic stress testing, and the still-unmeasured question of human learning efficacy.
