= Limitations

*No new efficacy evidence.* No human participants or live-provider performance results from the new skill loop are reported. The 16 archived model-role sessions and algebraic simulations describe the earlier evaluation regime. Local test success establishes specified software behavior, not better teaching or deployment reliability.

*Limited behavioral coverage.* The starter suite has 18 cases in two domains and evaluates the tutor's next continuation after a fixed learner prefix. It cannot observe a learner's reaction to changed teaching or test a full sequence of diagnosis, instruction, repair, and return visits. The CLI and browser allow different pedagogical tool subsets. Neither evaluator reproduces every model setting, tool, context source, voice mode, or UI state available to a live learner. Revision pinning controls instructional text; it does not freeze an external model's implementation or all surrounding product behavior.

*Judge validity and provenance.* Rubric judgments can favor style, verbosity, or familiar instructional language. The same model may act and judge in separate calls, and a transcript can contain attempts to influence evaluation. The adapter asks judges to treat transcripts as untrusted evidence, but that instruction is not a proof against manipulation. Saved records identify tutor model/runtime and criterion rationales; they do not yet provide a complete independently versioned judge configuration, calibration dataset, and inter-rater agreement study. Blinded human calibration remains necessary.

*Small and public holdouts.* Distinct family labels do not guarantee independent errors. The release cases are public source, not private evaluation material. Consumption records block ordinary reuse but cannot detect every semantic paraphrase or prevent a privileged developer from rewriting the store. The sign-test rule assumes conditions that the small authored suite has not empirically established; it is an eligibility check, not a lifetime error-rate guarantee. New holdout packs require independent authorship, and the browser has no operator-facing pack-renewal workflow yet.

*Incomplete longitudinal measurement.* Learner checks cover two topics with three items per stage. Parallel forms are not validated or equated, assistance is self-reported, and revision exposure is recorded by the operator. Missingness is explicit but may be systematic. No mechanism currently randomizes learners, controls outside help, or attributes a pre/post difference causally to a revision. Learner outcomes do not yet enter automatic promotion decisions.

*Bounded and local adaptation.* Only skill instructions evolve through the new gate. The hypothesis ledger has no demonstrated long-horizon consolidation benefit. CLI and browser state are separate; browser state has no account namespace or cross-device synchronization. A changed base persona needs its own evaluation. These constraints limit the scope of claims about a system that continually learns from all use.

*Historical evidence quality.* The archive is small, selected by a reproducible timestamp rule rather than a representative sampling design, and lacks scorer provenance. Its contamination detector is heuristic. The simulator's outcome names denote engineering equations, and its optimizer can exploit those equations. Keeping those analyses reproducible does not make them valid measurements of mastery, retention, or agency.
