import type { UiMusicLabNode } from "@keating/learner-contracts";
import { MUSIC_PLAYER_SCRIPT } from "./music-player";

export const STRUDEL_RUNTIME_PATH = "/vendor/strudel-web-1.3.0/index.js";

export function jsonForHtml(value: unknown): string {
	return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

/** Strudel evaluates only inside an opaque origin; its synth examples need no network. */
export function buildMusicDocument(code: string, origin: string, options: Pick<UiMusicLabNode, "controls" | "visualization"> = {}): string {
	const safeOrigin = new URL(origin).origin;
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src ${safeOrigin}${STRUDEL_RUNTIME_PATH} 'unsafe-inline' 'unsafe-eval' data: blob:; style-src 'unsafe-inline'; worker-src blob: data:; connect-src 'none'; media-src blob: data:"><style>
*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:#101914;color:#e3efe7;font:13px system-ui,sans-serif}main{display:grid;gap:14px;padding:16px}header{display:flex;justify-content:space-between;align-items:center;gap:10px}h2{margin:0;font-size:12px;letter-spacing:.04em;font-weight:500;color:#b2c6b9}figure{margin:0;padding:12px 6px 8px;background:#15231a;border:1px solid #304636;border-radius:10px}canvas{display:block;width:100%;height:174px}figcaption{padding:0 8px;min-height:16px;color:#a8beb0;font-size:11px;font-variant-numeric:tabular-nums}.toolbar{display:flex;gap:8px}button{display:inline-flex;justify-content:center;align-items:center;gap:6px;min-height:44px;padding:0 14px;border:1px solid #55735e;border-radius:8px;background:transparent;color:#e3efe7;font:600 13px system-ui;cursor:pointer}#play{background:#4be388;border-color:#4be388;color:#102018}button:hover:not(:disabled){filter:brightness(1.1)}button:focus-visible,summary:focus-visible{outline:2px solid #4be388;outline-offset:3px}button:disabled{opacity:.45;cursor:default}#status{min-height:18px;font-size:12px;color:#b2c6b9;margin:0}#controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px 24px}.control{display:block;min-width:0}.control:first-child:last-child{grid-column:1/-1}.control-label{display:flex;justify-content:space-between;align-items:baseline;gap:8px;font-size:12px}.control-label output{color:#b3f4cb;white-space:nowrap;font-variant-numeric:tabular-nums;font-size:11px}input[type=range]{display:block;width:100%;height:44px;margin:0;accent-color:#4be388;cursor:pointer;background:transparent}input[type=range]:focus-visible{outline:2px solid #4be388;outline-offset:0;border-radius:6px}summary{display:flex;align-items:center;gap:7px;min-height:44px;cursor:pointer;color:#b2c6b9;font-size:12px;list-style:none}summary:before{content:'+';font-size:16px}details[open]>summary:before{content:'−'}details{border-top:1px solid #304636}textarea{display:block;width:100%;height:225px;resize:vertical;padding:12px;border:1px solid #3b5143;border-radius:8px;outline:none;background:#101914;color:#e3efe7;font:14px/1.6 ui-monospace,monospace;tab-size:2;white-space:pre}textarea:focus{outline:2px solid #4be388;outline-offset:1px}.editor-label{display:block;font-size:11px;color:#a8beb0;margin-bottom:8px}table{width:100%;border-collapse:collapse;font-size:11px;text-align:left;font-variant-numeric:tabular-nums}th,td{padding:5px 8px;border-bottom:1px solid #263c2e}th{font-weight:500;color:#a8beb0}.notes-scroll{max-height:180px;overflow:auto}@media(max-width:420px){main{padding:12px;gap:12px}#controls{grid-template-columns:1fr;gap:0}canvas{height:160px}textarea{font-size:16px}button{padding:0 12px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style></head><body><main><header><h2 id="visual-title">Pattern</h2><div class="toolbar"><button id="play" disabled>▶ Play</button><button id="stop" disabled>■ Stop</button></div></header><figure><canvas id="visual" role="img"></canvas><figcaption id="visual-caption">Press Play to see the sound.</figcaption></figure><div id="controls"></div><p id="status" role="status" aria-live="polite">Loading Strudel…</p><details id="edit"><summary>Edit Strudel code</summary><label class="editor-label" for="code">Pattern · use controls.id to connect a slider</label><textarea id="code" spellcheck="false" autocapitalize="off" autocorrect="off"></textarea></details><details id="note-data"><summary>Note data</summary><div class="notes-scroll" tabindex="0" aria-label="Pattern note data"><table><thead><tr><th>Pitch</th><th>Start (cycle)</th><th>End (cycle)</th></tr></thead><tbody id="events"></tbody></table></div></details></main><script id="settings" type="application/json">${jsonForHtml({ code, ...options })}</script><script src="${safeOrigin}${STRUDEL_RUNTIME_PATH}"></script><script>${MUSIC_PLAYER_SCRIPT}</script></body></html>`;
}
