import { access, copyFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

const ARTIFACT_THEME_FILENAME = "keating-artifact-theme.css";

export const artifactThemeTokens = {
  paper: "#f1ece0",
  paperDeep: "#e9e2d2",
  card: "#f6f2e8",
  ink: "#1c211b",
  inkSoft: "#4a5247",
  accent: "#1e9b50",
  accentDim: "#14743c",
  greenWash: "#ddebdd",
  terminal: "#0c1510",
  terminalEdge: "#1b2a1f",
  phosphor: "#4be388",
  phosphorDim: "#2e9a5c",
  amber: "#e8a33d",
  red: "#d5604b"
} as const;

export const artifactScenePalette = {
  background: artifactThemeTokens.terminal,
  ink: "#dcefe0",
  accent: artifactThemeTokens.phosphor,
  support: artifactThemeTokens.accent,
  soft: artifactThemeTokens.greenWash,
  warning: artifactThemeTokens.amber
} as const;

export interface ArtifactTheme {
  cssPath: string;
  href: string;
  source: "panda" | "fallback";
}

function packageRoot(): string {
  const moduleUrl = (import.meta as unknown as { url: string }).url;
  const modulePath = decodeURIComponent(moduleUrl.replace(/^file:\/\//, ""));
  if (modulePath.includes("/dist/src/")) return modulePath.split("/dist/src/")[0];
  if (modulePath.includes("/src/")) return modulePath.split("/src/")[0];
  return join(dirname(modulePath), "../../../");
}

async function firstExisting(paths: string[]): Promise<string | null> {
  for (const path of paths) {
    try {
      await access(path);
      return path;
    } catch {
      // Try the next known Panda output location.
    }
  }
  return null;
}

export function fallbackArtifactThemeCss(): string {
  const t = artifactThemeTokens;
  return `/* Generated by Keating. Prefer replacing this file with the repo PandaCSS build output. */
:root {
  color-scheme: light;
  --paper: ${t.paper};
  --paper-deep: ${t.paperDeep};
  --card: ${t.card};
  --ink: ${t.ink};
  --ink-soft: ${t.inkSoft};
  --accent: ${t.accent};
  --accent-dim: ${t.accentDim};
  --green-wash: ${t.greenWash};
  --terminal: ${t.terminal};
  --terminal-edge: ${t.terminalEdge};
  --phosphor: ${t.phosphor};
  --phosphor-dim: ${t.phosphorDim};
  --amber: ${t.amber};
  --red: ${t.red};
  --line: rgba(28, 33, 27, 0.22);
  --line-soft: rgba(28, 33, 27, 0.12);
  --mono-display: "Space Mono", ui-monospace, "Cascadia Mono", Menlo, monospace;
  --mono-body: "JetBrains Mono", ui-monospace, "Cascadia Mono", Menlo, monospace;
  --shadow-card: 0 1px 0 rgba(28, 33, 27, 0.06), 0 10px 28px -18px rgba(28, 33, 27, 0.35);
  --radius: 0.25rem;
}

@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
    --paper: ${t.terminal};
    --paper-deep: #0a110d;
    --card: #11201a;
    --ink: #dcefe0;
    --ink-soft: #9dbfa8;
    --accent: ${t.phosphor};
    --accent-dim: ${t.phosphor};
    --green-wash: rgba(75, 227, 136, 0.12);
    --line: rgba(75, 227, 136, 0.28);
    --line-soft: rgba(75, 227, 136, 0.14);
    --shadow-card: 0 1px 0 rgba(0, 0, 0, 0.4), 0 10px 28px -18px rgba(0, 0, 0, 0.8);
  }
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100%;
}

body {
  background:
    radial-gradient(ellipse 70% 52% at 80% 0%, var(--green-wash), transparent 62%),
    var(--paper);
  color: var(--ink);
  font-family: var(--mono-body);
  line-height: 1.65;
  -webkit-font-smoothing: antialiased;
}

a {
  color: var(--accent-dim);
  font-weight: 700;
}

.keating-artifact {
  min-height: 100vh;
  padding: clamp(1rem, 3vw, 2.5rem);
}

.keating-artifact-shell {
  width: min(92vw, 1280px);
  margin: 0 auto;
  display: grid;
  gap: 1rem;
}

.keating-artifact-header {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: end;
  border: 1.5px solid var(--ink);
  background: var(--card);
  box-shadow: 4px 4px 0 var(--ink);
  padding: clamp(1rem, 2vw, 1.5rem);
}

.keating-artifact-title {
  margin: 0.25rem 0 0;
  color: var(--accent-dim);
  font-family: var(--mono-display);
  font-size: clamp(1.8rem, 4vw, 3.5rem);
  line-height: 1.05;
  letter-spacing: -0.025em;
}

.keating-artifact-meta {
  color: var(--ink-soft);
  font-size: 0.78rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

.keating-artifact-links {
  display: grid;
  gap: 0.35rem;
  justify-items: end;
  font-size: 0.86rem;
}

.keating-crt-panel {
  position: relative;
  overflow: hidden;
  border: 1.5px solid var(--ink);
  background: var(--terminal);
  color: var(--phosphor);
  box-shadow: 6px 6px 0 var(--ink);
}

.keating-crt-panel::after {
  content: "";
  position: absolute;
  inset: 0;
  pointer-events: none;
  background: repeating-linear-gradient(0deg, rgba(0, 0, 0, 0.16) 0 1px, transparent 1px 3px);
  mix-blend-mode: multiply;
}

@media (max-width: 720px) {
  .keating-artifact-header {
    align-items: start;
    flex-direction: column;
  }

  .keating-artifact-links {
    justify-items: start;
  }
}
`;
}

export async function prepareArtifactTheme(cwd: string, artifactDir: string): Promise<ArtifactTheme> {
  await mkdir(artifactDir, { recursive: true });
  const cssPath = join(artifactDir, ARTIFACT_THEME_FILENAME);
  const source = await firstExisting([
    join(cwd, "web", "styled-system", "styles.css"),
    join(cwd, "web", "src", "styled-system", "styles.css"),
    join(cwd, "styled-system", "styles.css"),
    join(packageRoot(), "web", "styled-system", "styles.css"),
    join(packageRoot(), "web", "src", "styled-system", "styles.css")
  ]);

  if (source) {
    await copyFile(source, cssPath);
    return {
      cssPath,
      href: importHref(artifactDir, cssPath),
      source: "panda"
    };
  }

  await writeFile(cssPath, fallbackArtifactThemeCss(), "utf8");
  return {
    cssPath,
    href: importHref(artifactDir, cssPath),
    source: "fallback"
  };
}

function importHref(fromDir: string, targetPath: string): string {
  const href = relative(fromDir, targetPath).replaceAll("\\", "/");
  return href.startsWith(".") ? href : `./${href}`;
}
