#!/usr/bin/env bun
/**
 * Bundles mutable source files into a Node.js module for NodePod boot.
 *
 * Usage:
 *   bun scripts/generate-nodepod-boot-files.ts
 *
 * For every .ts file we emit both the raw TS (for agent editing) and a
 * transpiled .js counterpart (for NodePod require()). Transpilation uses
 * Bun's built-in TS→JS transformer which handles types, generics, decorators,
 * and ESM/CJS correctly.
 */

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { join, relative } from "node:path";

const SOURCE_DIRS = ["src/core", "pi/prompts", "web/src/keating"];
const OUTPUT_FILE = "web/src/keating/nodepod-boot-files.ts";
const INCLUDE_PATTERNS = [/\.ts$/, /\.md$/, /\.py$/, /\.sh$/, /\.txt$/];
const EXCLUDE_PATTERNS = [
  /\.test\.ts$/,
  /\.spec\.ts$/,
  /node_modules/,
  /web\/src\/keating\/nodepod-boot-files\.ts$/,
];

async function* walkDir(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === "dist" || entry.name === ".output") continue;
      yield* walkDir(fullPath);
    } else {
      yield fullPath;
    }
  }
}

/** Use Bun's built-in transpiler for TS → JS. */
function transpileWithBun(source: string, filename: string): string {
  try {
    // @ts-ignore — Bun.Transpiler is a Bun-specific API
    const transpiler = new Bun.Transpiler({
      loader: "ts",
      target: "browser",
      tsconfig: {
        compilerOptions: {
          module: "NodeNext",
          moduleResolution: "NodeNext",
          target: "ES2022",
          strict: true,
        },
      },
    });
    return transpiler.transformSync(source, filename);
  } catch {
    return source; // fallback: return raw source
  }
}

async function main() {
  const files = new Map<string, string>();
  const rootDir = process.cwd();

  for (const dir of SOURCE_DIRS) {
    try {
      for await (const filePath of walkDir(dir)) {
        const rel = relative(rootDir, filePath).replace(/\\/g, "/");
        const include = INCLUDE_PATTERNS.some((p) => p.test(rel));
        const exclude = EXCLUDE_PATTERNS.some((p) => p.test(rel));
        if (!include || exclude) continue;
        const content = await readFile(filePath, "utf8");
        files.set(rel, content);

        // Transpile .ts → .js using Bun's built-in transformer
        if (rel.endsWith(".ts") && !rel.endsWith(".d.ts")) {
          const jsPath = rel.replace(/\.ts$/, ".js");
          const jsContent = transpileWithBun(content, rel);
          files.set(jsPath, jsContent);
        }
      }
    } catch (e: any) {
      console.warn(`Warning: could not read ${dir}: ${e.message}`);
    }
  }

  // Sort for deterministic output
  const sorted = Array.from(files.entries()).sort(([a], [b]) => a.localeCompare(b));

  const lines = [
    "// AUTO-GENERATED by scripts/generate-nodepod-boot-files.ts",
    "// Do not edit manually. Run the script to regenerate.",
    "",
    "export interface NodePodBootFile {",
    "  path: string;",
    "  content: string;",
    "}",
    "",
    "export const NODEPOD_BOOT_FILES: Record<string, string> = {",
  ];

  for (const [path, content] of sorted) {
    const escaped = JSON.stringify(content);
    lines.push(`  ${JSON.stringify(path)}: ${escaped},`);
  }

  lines.push("};");
  lines.push("");
  lines.push(`export const NODEPOD_BOOT_FILE_COUNT = ${sorted.length};`);
  lines.push("");

  // Helper: get JS counterpart for a TS path
  lines.push("/** For a given .ts path, return its transpiled .js counterpart if it exists. */");
  lines.push("export function getJsCounterpart(tsPath: string): string | null {");
  lines.push('  const jsPath = tsPath.replace(/\\.ts$/, ".js");');
  lines.push('  return NODEPOD_BOOT_FILES[jsPath] ? jsPath : null;');
  lines.push("}");
  lines.push("");

  // Helper: on-demand transpile (for agent-edited files not in boot bundle)
  lines.push(`export const TRANSPILER_BANNER = "// Transpiled by Bun.Transpiler\\n";`);
  lines.push("");

  await mkdir("web/src/keating", { recursive: true });
  await writeFile(OUTPUT_FILE, lines.join("\n"), "utf8");

  const totalBytes = sorted.reduce((sum, [, c]) => sum + c.length, 0);
  const jsCount = sorted.filter(([p]) => p.endsWith(".js")).length;
  console.log(`Generated ${OUTPUT_FILE} with ${sorted.length} files (${Math.round(totalBytes / 1024)} KB total, ${jsCount} JS transpiled via Bun)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
