plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.diogenesoftoronto.keating'
version = '1.0.0'

android {
  namespace 'com.diogenesoftoronto.keating.litert'
  defaultConfig {
    minSdkVersion 26
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation project(':keating-litert-sdk')
}
