= Findings: what Keating taught its creator
Keating helps its creator resolve specific conceptual errors and develop more precise explanations. Its assessment of that progress is less reliable: it sometimes announces understanding while important misconceptions remain. The creator repeatedly supplies the information that makes instruction useful: an actual error, an explanation in their own words, a correction to the tutor, or a report that an interaction failed. The central pattern is *mutual correction during development*.

The selected substantive lessons concern static embeddings, Scheme and Guix, graphics APIs, latent reasoning, and policy-gradient notation. Shorter contrasting episodes concern jazz, urban geography, free will, and the relationship between AI and compilers. The recurring goal is practical mechanism-level understanding: how a thing works well enough to build, debug, evaluate, or explain it. The curriculum grows from the creator's projects and reading, with Keating constructing lessons around the question at hand.

== Finding 1: concrete reconstruction changes the learner's explanation
In the static-embedding episode (E1), the creator initially insists that an encoder produces a single merged vector. Keating contrasts the per-token matrix with the pooling operation. The creator then extrapolates to a 1,000-token input, identifies mean pooling, and explains the contextual information lost when attention is removed. Later, they infer the low cost of gradients through a lookup table. They also articulate the memory/computation benefits of shorter embeddings in response to the tutor's explicit cues. The gradient observation is a spontaneous deduction; the benefits response is prompted elaboration. Together, these responses trace how the creator builds a more precise account of the mechanism.

The Guile debugging episode (E2) provides another concrete transition. The creator initially interprets “Wrong type to apply: 1” as an argument-count or list-type problem. After discussing operator position, they repair the nested-list expression. On a fresh `double` example they identify the non-procedure call, then distinguish that error from an arity error. Their first proposed fix is still wrong, and Keating correctly uses it to expose the next distinction. Their final reconstruction still reverses the backtrace frame order, which the tutor corrects. Successive mistakes give the tutor precise information about what to teach next.

*Interpretation.* Keating's strongest teaching mechanism in these episodes is small-scale reconstruction: ask the creator to predict or explain an inspectable example, identify the error in the response, and use it to choose the next example. The resulting dialogue develops the creator's explanation one distinction at a time. The distinction between elaboration and repetition follows self-explanation research @chi1994. Human-tutoring studies likewise locate substantial instructional work in constructive learner responses @chi2001.

#pagebreak()
= A close view of one learning trajectory
#figure(image("figures/learning-path.svg", width: 100%), caption: [Selected stages from E1, tracing the creator's changing explanation and new deductions.])

The same trajectory exposes a pacing failure. The creator explicitly says that the contrastive-learning question is too basic for their existing knowledge. Keating continues its planned sequence and only later returns to the engineering question that motivated the visit. The retained episode ends with the tutor's final questions unanswered. The lesson advances the creator's understanding while spending time on material they already know. An adaptive tutor should use demonstrated knowledge to shorten the route to the learner's question.

#pagebreak()
= Findings: where the teaching overstates or misreads progress
== Finding 2: recognition is repeatedly mistaken for knowledge
In both the initial SwiReasoning discussion (E3a) and the Vulkan diagnostic (E4), the creator explains that a correct option was selected because it sounded plausible. In the Vulkan case they specifically identify the longest, most obvious-looking option as the clue. Keating acknowledges the creator's explanation. These diagnostics rewarded recognition of the answer's wording before establishing knowledge of the underlying concept. Correct guesses still offer opportunities for learning: feedback improves later recall of low-confidence correct answers @butler2008. The problem is declaring the diagnostic complete.

The creator returns to SwiReasoning about 17 days after the initial, unfinished exchange (E3b). They ask to start from the ground up and cannot reconstruct the core claim beyond a vague association with controlling reasoning or test-time compute. The revisit exposes a concrete recall failure. Keating retrieves an old plan but fails to recover a precise learner-specific stopping point. It preserves the lesson artifact more successfully than the state needed to resume teaching. Retrieval experiments show why this later reconstruction matters: immediate performance and delayed retention can favor different instructional conditions @roediger2006.

== Finding 3: useful analogies coexist with premature mastery claims
In the Vulkan lesson (E4), the creator develops a cookbook-versus-improvising-chef analogy and reasons that a trivial ten-triangle workload need not benefit from the more explicit API. These responses explain work allocation and connect the API's value to workload. The tutor repeatedly declares that the creator now owns the material before later questions expose unresolved understanding of driver state tracking and async compute.

The quiz also becomes entangled with interface and grading problems. The creator attributes a blank response to a broken input, and the tutor reports a truncation-related grading error on another answer. After the apparent success, the creator still asks what state tracking actually means. Keating had allowed explanatory vocabulary to stand in for an understood mechanism. Its praise tracked participation more closely than completed understanding. Research on explanatory depth supports probing mechanisms before certifying understanding @rozenblit2002. Here, the premature judgment belongs to the tutor; the creator exposes the gap.

== Finding 4: the creator also corrects the teacher's interpretation
In the policy-gradient episode (E5), the creator first requests plain-English explanations and a symbol glossary. After clarifying absolute value, they apply the update rule to a recommendation example. When they describe a lower-ranked category losing relative visibility, Keating initially corrects them by pointing to its positive logit update. The creator clarifies that the claim concerns relative share, and the tutor concedes it over-corrected. The creator's distinction is substantively useful: increasing a logit does not guarantee increasing its softmax probability. Contesting the evaluation repairs the tutor's interpretation and keeps the lesson focused on the distinction the creator actually made.

#pagebreak()
= Findings: correctness and instructional maintenance
== Finding 5: confident teaching introduces executable mistakes
The Guile episode ends with a purported clean `sum-all` reference implementation whose recursive call passes a list as one argument to a variadic procedure. Consequently the rest-argument list contains that list as an element; the empty-argument base case is not reached. The export labels the defective turn Fireworks GLM-5.2 and the session MiniMax-M3. A local Guile reproduction of the supplied implementation did not terminate within a two-second limit on a three-argument example. A list-recursive helper returned the expected results 0, 4, and 6 for empty, mixed, and numeric inputs. The GNU Guile manual's rest-argument semantics explain the nesting; a local probe also confirmed that passing an empty list produces a rest list containing one empty list.

In the same episode, Keating endorses the creator's `case` explanation but incorrectly describes `(integer?)` in a clause as comparing against a procedure object. A local Guile probe instead matches the literal symbol `integer?`, consistent with `case` datum matching. The high-level choice of `cond` for predicate tests was useful; the explanation of why was wrong. In the Guix packaging lesson (E6), the tutor also recommends `guix edit` on build-system names; the creator tries the guidance and reports that it only works for packages. Keating then corrects its advice. Across these examples, fluent instruction includes technical errors that emerge through execution or the creator's own testing.

*Interpretation.* These errors undermine the creator's goal of understanding code well enough to work independently. The creator catches and challenges some faulty guidance during the lessons; the local reproduction catches an additional defect in the reference implementation. Programming instruction needs executable checks on the examples it asks a learner to trust.

== Finding 6: the creator performs substantial instructional maintenance
The creator repeatedly requests the question tool, reports broken maps and animations, asks for omitted lesson plans or verification, and distinguishes input failures from knowledge gaps. The free-will episode (E7) is dominated by getting the map and expected supporting artifacts produced. The cities episode (E8) shifts from a question interface that cannot submit to a quiz representation. In the packaging and graphics lessons, repair interrupts the substantive thread.

Instructional maintenance is a substantial part of the creator's learning experience. The creator is simultaneously learner, evaluator, and designer: they recognize intended behavior, insist on it, and preserve useful feedback about failures. Their persistence keeps several lessons moving through broken interactions. It also makes the work of operating and improving Keating inseparable from the work of learning through it. This overlap of sustained personal use and system development situates the case in autobiographical design @neustaedter2012.

Reference for the reproduced Scheme semantics: #link("https://www.gnu.org/software/guile/manual/guile.html")[GNU Guile Reference Manual], sections on procedure arguments and conditional evaluation.

#pagebreak()
= Learning through a developing application
#figure(image("figures/development-timeline.svg", width: 100%), caption: [Parallel tracks of lesson evidence and repository development across the study period.])

#pagebreak()
= Application changes reshape the learning experience
Repository history documents substantive changes during the observed lessons: the 9 June quiz and fork overhaul (`0393c402`), 15 June flashcard and reward-export work (`0ad089e3`), and 28 June model-judged open-answer grading (`16174935`). July includes an animation-serving fix (`669b26b8`), migration to Hyperframes (`b97c7e8e`), and streamed teaching interfaces with structured learner-response work (`478d4633`). The system prompt was rewritten for autonomous tool use on 8 August (`8b5efb21`). September's fresh teaching gates and fixed-check work appears in the 3.12 release (`bce0173c`); this draft adds selectable export judging.

These changes alter both the learning experience and the instrument recording it. Open-answer grading changes how the creator explains an idea and receives feedback. Rendered lesson widgets change how material is presented and answers are submitted. Reward exports change which interactions become training records. The case follows these developments alongside the lessons because the evolving interface, feedback, and records are part of the experience under study.

The transcripts document how the creator encounters the implementation: black or non-embedded animation, a subsequent HTML attempt, a question that cannot submit, and a replacement quiz representation. These exchanges show the application being repaired within a lesson. Repository history supplies the parallel record of changes to the product's capabilities.

*Overall assessment.* For its creator, Keating functions as a productive but uneven partner for understanding mechanisms. Its best interactions elicit an explanation, expose a specific misconception, and let the creator reason about a new case. Its weaknesses are overconfident feedback, insufficiently checked technical content, teaching sequences that persist after the creator signals familiarity, and interface failures that require the creator to manage the lesson. The creator learns through the tool while also supplying the criticism and repair work that keep its teaching useful.

The findings point to a concrete development priority: shorten the loop from the creator's response to a checked interpretation, a working interaction, and a later revisit of the same unresolved idea. Keating's strongest lessons already demonstrate the value of that loop. Improving its assessment, technical verification, and continuity would address the failures that repeatedly interrupt it.
