= Prior work and the contribution of this case
The earlier technical report, _Keating: A Metaharness for Agency-Preserving AI Instruction_, describes the teaching architecture, revision gates, and reproducibility checks @keating2026methods. Its evidence includes model-to-model traces and deterministic policy analyses. The present study supplies a complementary account of actual creator use: how explanations change during lessons, how the learner corrects the teacher, and how application development changes the encounter. Its distinctive contribution is the longitudinal relationship between learning a subject and building the system that teaches it.

== Learning while designing the teacher
Neustaedter and Sengers define autobiographical design as “design research drawing on extensive, genuine usage by those creating or building the system” #cite(<neustaedter2012>, supplement: [p. 514]). This is a close fit to Keating's creator learning with the application while revising it. A broken question input, a useful explanation, and a request for a missing animation all belong to the same experience. The creator's dual role gives the study access to instructional needs and repair work that a short, fixed-system usability session would miss.

== Explanations, correct answers, and later reconstruction
Self-explanation research provides a vocabulary for the changes visible in the embedding and Scheme lessons. In an experiment with 24 eighth graders studying circulation, students prompted to explain the text showed larger pre/post gains than students who read it twice @chi1994. The important distinction was between reproducing wording and constructing an account that connects ideas. Human-tutoring research likewise examined constructive learner contributions separately from acknowledgments and the amount of explanation supplied by the tutor @chi2001. In this case, a new inference or a precise objection reveals what the creator understands and gives the teacher material for its next response.

Correctness alone leaves part of that evidence hidden. Butler and colleagues tested multiple-choice answers together with confidence and subsequent answer production. Feedback improved retention even when an initially correct answer had been a low-confidence guess @butler2008. The implication for Keating is to follow a correct selection with feedback and a request for reasoning. The problem in the selected diagnostics is the tutor's decision to treat selection as completed understanding.

Research on explanatory depth adds a related assessment principle. Participants' ratings of their knowledge of familiar devices fell after they attempted detailed explanations @rozenblit2002. The Vulkan episode places the calibration problem in the teacher's judgment: Keating declares mastery while the creator continues to identify missing mechanisms. Requiring a mechanism-level explanation would make that judgment answerable to the learner's actual account.

“Testing is a powerful means of improving learning, not just assessing it,” write Roediger and Karpicke #cite(<roediger2006>, supplement: [p. 249]). In their prose-learning experiments, restudy produced better immediate recall, while retrieval practice produced better recall after a delay. That result gives the later SwiReasoning reconstruction a distinct place in this study and motivates scheduled follow-up assessments.

#pagebreak()
= What comparative AI-tutoring studies establish
Recent experiments show why the instructional arrangement around a model matters. In a randomized crossover study of 194 university physics students, a structured AI tutor produced higher immediate post-test scores than an active-learning classroom condition: medians were 4.5 and 3.5 respectively @kestin2025. The tutor used prepared solutions, targeted feedback, self-pacing, and an interface that sequenced multipart problems. Keating's maps, questions, feedback, and interfaces similarly organize the teaching encounter; their reliability and sequencing are part of the pedagogical design.

A different result appears when assistance is removed. In a randomized study with nearly 1,000 high-school mathematics students, ordinary GPT-4 assistance and a teacher-informed GPT Tutor improved practice performance by 48% and 127%, respectively. On subsequent unaided exams, the ordinary GPT group scored 17% below control, while the GPT Tutor group was statistically indistinguishable from control @bastani2025. These findings make separate assisted and unaided measurements a central design requirement. In Keating's record, successful dialogue, correct selections, and later reconstruction therefore receive separate analyses.

Human oversight also changes the instructional arrangement. Tutor CoPilot supplied AI suggestions to human tutors in a randomized field study. Access increased the probability of passing a session exit ticket by four percentage points @wang2025. Keating places more of the oversight inside the learner's role: its creator challenges explanations, repairs interactions, and redirects lessons. Recording this corrective labor helps explain how useful instruction was achieved and what the application required from its user.

== From an observed problem to a tested revision
WikiSkill separates raw agent traces, accumulated knowledge, and deployable skills, then evaluates proposed updates through validation and rollback @tang2026wikiskill. Its experiments also examine interactions between skills and model capability. This supplies a systems precedent for preserving the creator's lesson evidence, recording a specific teaching hypothesis, and testing a revision across model configurations. The learning question then concerns what the revised teaching enables a person to explain, retain, and use.

The evaluator is part of that configuration. Zheng and colleagues report that absolute grading scores “are likely to fluctuate more than relative pairwise results if the judge model changes” #cite(<zheng2023>, supplement: [p. 4]). They also examine answer-order bias, verbosity, and reasoning errors. For Keating, recording the selected judge makes the scoring configuration explicit. Calibration compares its judgments against checked examples and human ratings. The faulty Scheme reference and premature mastery judgments supply concrete examples for that calibration set.

Together, these studies direct the analysis toward the work done in each exchange: the learner constructs an explanation, the teacher interprets it, the interface supports the next attempt, and a later assessment tests what remains. The case adds a record of that process as its creator, application, and underlying models develop together.
