#set page(paper: "us-letter", margin: (x: 1in, y: 1in))
#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true)

#align(center)[
  #block(text(weight: "bold", size: 1.5em)[
    Cognitive Empowerment in the Age of Automation: \
    A Hyperteacher Framework for Preserving the Human Voice
  ])
  #v(1em)
  #text(style: "italic")[The Keating Research Group] \
  #datetime(year: 2026, month: 4, day: 2).display("[month repr:long] [day], [year]")
]

#v(2em)

#block(fill: luma(240), inset: 1em, radius: 4pt)[
  *Abstract:* As large language models (LLMs) become ubiquitous, the primary risk to education is the "surrogate thought" problem—where learners offload cognitive labor to automated systems, achieving task completion at the expense of internalized understanding. This paper introduces *Keating*, a hyperteacher scaffold designed to enforce cognitive friction and ensure that technology serves as a bridge to independent human articulation ("The Voice"). We detail a deterministic artifact-oriented architecture that prioritizes "Voice Divergence" over "Surface Agreement."
]

== 1. Introduction: The Crisis of Surface Agreement

In the current educational landscape, AI is frequently used as a shortcut to the "Done" state. Students receive answers that are syntactically perfect but semantically hollow. This leads to *Surface Agreement*: a state where the learner can repeat a derivation or summary without the ability to reconstruct the underlying logic in their own identity.

Whitman's "powerful play" requires that each individual contributes a "verse." If that verse is generated by a black-box model, the identity of the contributor is lost. Keating exists to defend that identity.

== 2. The Hyperteacher Architecture

Keating differs from standard "tutor bots" by separating the interaction layer from the pedagogical logic:

- *Deterministic Scaffolding:* Lesson plans and meaning maps are generated as human-readable markdown and Mermaid artifacts. This ensures the AI's "teaching path" is inspectable and grounded.
- *Chain-of-Verification (CoVe):* To combat hallucination, Keating employs a multi-step cross-consistency check, ensuring that the factual core taught to the human is verified against independent research loops.
- *Semantic Divergence Checking:* The system explicitly measures the distance between the teacher's explanation and the learner's reconstruction. A high overlap is penalized as rote echo; success is measured by the learner's ability to find a new analogy.

== 3. Methodology: Reclaiming the Voice

The core of the Keating interaction is the "Mandate of Divergence." The system is instructed to:
1. Reject simple "Yes" or "I understand" responses.
2. Force the learner to carry the concept into a disparate domain (Transfer Pressure).
3. Identify rote repetition of the AI's own phrases and demand a re-articulation in the learner's "Own Voice."

#v(2em)
#align(center)[
  _... [Ongoing Research: Synthetic Learner Benchmarking results to follow] ..._
]
