# /// script
# requires-python = ">=3.12"
# dependencies = ["marimo==0.23.1", "pandas==2.*", "numpy>=2,<3", "matplotlib==3.10.*"]
# ///
"""Local paired PPO report exploration. No inference, scoring, network, or writes."""
import marimo

__generated_with = "0.23.1"
app = marimo.App(width="medium")


@app.cell
def _():
    import os
    import sys
    from pathlib import Path
    import marimo as mo
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root / "scripts/training"))
    import native_update_report as reports
    default_report = os.environ.get("KEATING_NATIVE_UPDATE_REPORT", str(
        root / ".keating/native-learning/model-stage-zero/native-update-report-v1/report.json"))
    return Path, default_report, mo, np, pd, plt, reports


@app.cell
def _(default_report, mo):
    report_path = mo.ui.text(value=default_report, label="Local report.json", full_width=True)
    mo.vstack([mo.md("""# What changed after the PPO update?

    Read the paired observations, unknowns and reviewer caveats together.
    Frozen criterion passes do not establish overall correctness. These authored
    tasks do not measure human learning or causal efficacy.

    This notebook reads the report generated by `native_update_report.py`.
    It never dispatches a request, changes a review, or writes an artifact.
    """), report_path])
    return (report_path,)


@app.cell
def _(Path, mo, report_path, reports):
    _path = Path(report_path.value).expanduser()
    mo.stop(not _path.is_file(), mo.md("No local report yet. Generate the report using the command in `docs/native-update-report.md`, or select its `report.json` here."))
    _error = None
    artifact = None
    try:
        artifact, _ = reports.read_report_evidence(_path)
        reports.check_report_seal(artifact, "report_hash")
        if artifact.get("kind") != "native-update-report" or artifact.get("schema_version") != 1:
            raise ValueError("Expected native-update-report schema 1")
    except (ValueError, OSError) as _exc:
        _error = str(_exc)
    mo.stop(_error is not None, mo.md(f"Invalid local report: `{_error}`"))
    return (artifact,)


@app.cell
def _(artifact, mo, pd):
    mo.vstack([
        mo.md(f"## {artifact['headline']}\n\n{artifact['fully_observed_tied_cases']} fully observed tied cases; {artifact['independent_family_count']} families."),
        mo.md("**Rubric blind spots and post-hoc observations:** the supplied reviewer rationales may identify factual errors outside the frozen checks. Read them separately from the unchanged criterion counts."),
        mo.ui.table(pd.DataFrame(artifact["posthoc_reviewer_observations"]), selection=None),
        mo.md("### Planned and observed denominators"),
        mo.ui.table(pd.DataFrame(artifact["denominators"]), selection=None),
    ])
    return


@app.cell
def _(artifact, plt, reports):
    figures = reports.plot_update_report(artifact)
    for _figure in figures.values():
        plt.close(_figure)  # Keep the rendered object, release pyplot's registry.
    return (figures,)


@app.cell
def _(artifact, figures, mo, pd):
    mo.vstack([figures["criteria"],
        mo.md("Only matched known criteria contribute to a paired difference. Unknown is not false."),
        mo.ui.table(pd.DataFrame(artifact["paired"]), selection=None),
        figures["tokens"],
        mo.md("Usage comes from the supplied OpenAI completion. No text retokenization fills missing counts.")])
    return


@app.cell
def _(artifact, figures, mo, np, pd):
    _update = artifact["update"]
    _tokens = pd.DataFrame(_update["tokens"])
    _outside = None if _update["epsilon"] is None else int(np.count_nonzero(
        _tokens["ratio_outside_clip_bounds"].to_numpy())) if not _tokens.empty else 0
    mo.vstack([figures["completion-diagnostics"],
        mo.md(f"**{_update['completion_tokens']} original completion positions**; outside recorded ratio bounds: {_outside if _outside is not None else 'unknown'}. Each capture also retains its own denominator below."),
        mo.ui.table(pd.DataFrame(_update["captures"]), selection=None),
        mo.md("These are **pre-optimizer student versus behavior scores**. They do not measure the updated checkpoint's probability change. Sign-aware surrogate clipping differs from simply being outside a ratio bound."),
        mo.md("### Raw provider metrics — reduction scope unverified\n\nThese may include masked prompt positions with zero-padded behavior values. They are kept separate from completion-only metrics."),
        mo.ui.table(pd.DataFrame([{"metric": k, "raw_value": v} for k, v in _update["raw_provider_metrics"].items()]), selection=None),
    ])
    return


@app.cell
def _(artifact, mo):
    case_choice = mo.ui.dropdown(options=[case["id"] for case in artifact["cases"]],
        value=artifact["cases"][0]["id"], label="Inspect task and responses")
    case_choice
    return (case_choice,)


@app.cell
def _(artifact, case_choice, mo, pd):
    _case = next(case for case in artifact["cases"] if case["id"] == case_choice.value)
    _rows = [row for row in artifact["rows"] if row["case_id"] == case_choice.value]
    mo.vstack([mo.plain_text(_case["actor"]["opening_message"]),
        mo.ui.table(pd.DataFrame(_case["evaluation_only"]["criteria"]), selection=None),
        *[mo.vstack([mo.md(f"**{row['arm']}** · {row['status']}"),
            mo.json(row["response"]), mo.plain_text(row["rationale"] or "Review unknown"),
            mo.ui.table(pd.DataFrame([{"criterion": k, "judgment": v} for k, v in row["criteria"].items()]), selection=None)]) for row in _rows],
        mo.md("### Limitations\n\n" + "\n\n".join(artifact["limitations"]))])
    return


if __name__ == "__main__":
    app.run()
