# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "numpy>=2,<3",
#     "marimo==0.23.1",
#     "matplotlib==3.10.*",
#     "pandas==2.*",
# ]
# ///
"""The published study analysis, read from its versioned JSON bundle.

Input is docs/generated/study-analysis.json, regenerated by
`devenv tasks run keating:study-analysis`. This notebook only reads it.
"""

import marimo

__generated_with = "0.23.1"
app = marimo.App(width="medium")


@app.cell
def _():
    import json
    from pathlib import Path

    import marimo as mo
    import matplotlib.pyplot as plt
    import pandas as pd

    project_root = Path(__file__).resolve().parents[1]
    analysis_path = project_root / "docs" / "generated" / "study-analysis.json"
    data = json.loads(analysis_path.read_text())

    # House palette, matching scripts/render-case-study-charts.py.
    INK, MUTED, GRID = "#254e63", "#536570", "#dce4e8"
    BLUE, TEAL, ORANGE = "#0072B2", "#00836B", "#C97900"
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "text.color": INK,
        "axes.labelcolor": MUTED,
        "xtick.color": MUTED,
        "ytick.color": INK,
        "axes.edgecolor": GRID,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.spines.left": False,
        "axes.titlesize": 12,
        "axes.titleweight": "bold",
        "axes.titlecolor": INK,
        "figure.facecolor": "white",
        "savefig.facecolor": "white",
        "svg.hashsalt": "keating-study-analysis-notebook-v1",
    })

    return BLUE, INK, ORANGE, TEAL, data, mo, pd, plt


@app.cell
def _(data, mo):
    external = data["externalEvaluation"]
    synthetic = data["syntheticBenchmark"]
    integrity = data["dataIntegrity"]

    mo.md(
        f"""
        # Keating Study Analysis

        This notebook reads the derived analysis bundle at
        `docs/generated/study-analysis.json`.

        - Raw trace files: **{integrity["rawTraceCount"]}**
        - Latest retained topic × learner pairs: **{integrity["latestTraceCount"]}**
        - Duplicate earlier traces excluded: **{integrity["excludedDuplicateTraceCount"]}**
        - Score corrections applied: **{len(external["scoreCorrections"])}**
        - External evaluation mean overall score: **{external["overall"]["mean"]}**
        - Synthetic full-suite delta over default: **{synthetic["benchmarkSummary"]["deltaOverall"]["mean"]}**
        """
    )
    return


@app.cell
def _(data, pd):
    topic_df = pd.DataFrame(data["externalEvaluation"]["topicSummary"])
    topic_df["overall_mean"] = topic_df["overall"].map(lambda row: row["mean"])
    topic_df["overall_low"] = topic_df["overall"].map(lambda row: row["ciLow"])
    topic_df["overall_high"] = topic_df["overall"].map(lambda row: row["ciHigh"])

    learner_df = pd.DataFrame(data["externalEvaluation"]["learnerSummary"])
    learner_df["overall_mean"] = learner_df["overall"].map(lambda row: row["mean"])

    ablation_df = pd.DataFrame(data["syntheticBenchmark"]["oneAtATimeAblations"])
    runs_df = pd.DataFrame(data["syntheticBenchmark"]["runs"])
    records_df = pd.DataFrame(data["externalEvaluation"]["records"])

    return ablation_df, learner_df, records_df, runs_df, topic_df


@app.cell
def _(mo, topic_df):
    mo.md("## External Evaluation by Topic")
    topic_df[["topic", "n", "overall_mean", "overall_low", "overall_high"]]
    return


@app.cell
def _(BLUE, INK, plt, topic_df):
    fig_topic, ax_topic = plt.subplots(figsize=(7, 4))
    ax_topic.barh(topic_df["topic"], topic_df["overall_mean"], color=BLUE)
    low = topic_df["overall_mean"] - topic_df["overall_low"]
    high = topic_df["overall_high"] - topic_df["overall_mean"]
    ax_topic.errorbar(
        topic_df["overall_mean"],
        topic_df["topic"],
        xerr=[low, high],
        fmt="none",
        ecolor=INK,
        capsize=3,
    )
    ax_topic.set_xlim(0, 1)
    ax_topic.set_xlabel("Mean overall score")
    ax_topic.set_ylabel("")
    ax_topic.set_title("External evaluation topic means with bootstrap intervals")
    fig_topic.tight_layout()
    fig_topic
    return


@app.cell
def _(mo, learner_df):
    mo.md("## External Evaluation by Learner Model")
    learner_df[["learner", "n", "overall_mean"]]
    return


@app.cell
def _(TEAL, plt, runs_df):
    fig_delta, ax_delta = plt.subplots(figsize=(7, 4))
    ax_delta.hist(runs_df["deltaOverall"], bins=20, color=TEAL, edgecolor="white")
    ax_delta.set_xlabel("Current policy minus default policy")
    ax_delta.set_ylabel("Seed count")
    ax_delta.set_title("Synthetic full-suite improvement across 200 seeds")
    fig_delta.tight_layout()
    fig_delta
    return


@app.cell
def _(ablation_df, mo):
    mo.md("## One-at-a-Time Synthetic Ablations")
    ablation_df
    return


@app.cell
def _(ORANGE, plt, ablation_df):
    fig_ablation, ax_ablation = plt.subplots(figsize=(7, 4.5))
    ordered = ablation_df.sort_values("meanDelta")
    ax_ablation.barh(ordered["field"], ordered["meanDelta"], color=ORANGE)
    ax_ablation.set_xlabel("Mean delta versus default")
    ax_ablation.set_ylabel("")
    ax_ablation.set_title("Single-parameter swaps into the default policy")
    fig_ablation.tight_layout()
    fig_ablation
    return


@app.cell
def _(mo, records_df):
    mo.md("## Record-Level Audit View")
    records_df[
        [
            "topic",
            "learner",
            "overall",
            "mastery",
            "engagement",
            "clarity",
            "features",
        ]
    ]
    return


if __name__ == "__main__":
    app.run()
