import {
  isContractTimestamp,
  validateLearnerGoal,
  validateLearnerQuestionCheck,
  validateLearnerQuizResult,
  validatePortableLearnerData,
  type CardReviewRecord,
  type GoalStepStatus,
  type LearnerGoal,
  type LearnerQuestionCheck,
  type LearnerQuizResult,
  type PortableLearnerData,
  type SrsRating,
  type StudyPriority,
  type StudyPriorityRecord,
  type StudyPriorityTargetType,
} from "@keating/learner-contracts";
import { applyPortableCardReview, createStudyPriority } from "./learner-study";

export interface CardReviewMutationResult {
  data: PortableLearnerData;
  review: CardReviewRecord;
}

export interface StudyPriorityMutationResult {
  data: PortableLearnerData;
  record: StudyPriorityRecord;
}

function requireValidSource(data: PortableLearnerData): void {
  if (!validatePortableLearnerData(data)) throw new Error("Cannot mutate invalid portable learner data.");
}

function requireValidResult(data: PortableLearnerData): PortableLearnerData {
  if (!validatePortableLearnerData(data)) throw new Error("Learner mutation would create invalid portable learner data.");
  return data;
}

function requireMutationTimestamp(nowIso: string): void {
  if (!isContractTimestamp(nowIso)) throw new Error("Learner mutation requires a canonical UTC timestamp.");
}

/** Stable structural comparison so JSON key insertion order cannot turn a retry into a conflict. */
function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (!value || typeof value !== "object") return JSON.stringify(value);
  return `{${Object.entries(value as Record<string, unknown>)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, entry]) => `${JSON.stringify(key)}:${stableJson(entry)}`)
    .join(",")}}`;
}

function sameRecord(left: { id: string }, right: { id: string }): boolean {
  return left.id === right.id && stableJson(left) === stableJson(right);
}

/** Goal status and revision time are learner-owned progress, not card identity. */
function sameGoalSource(left: LearnerGoal, right: LearnerGoal): boolean {
  return left.id === right.id && stableJson({
    title: left.title,
    description: left.description,
    steps: left.steps.map((step) => ({
      id: step.id,
      title: step.title,
      successCriteria: step.successCriteria,
    })),
  }) === stableJson({
    title: right.title,
    description: right.description,
    steps: right.steps.map((step) => ({
      id: step.id,
      title: step.title,
      successCriteria: step.successCriteria,
    })),
  });
}

/** Result creation time may be regenerated by a replay; answer evidence may not. */
function sameQuizEvidence(left: LearnerQuizResult, right: LearnerQuizResult): boolean {
  return left.id === right.id && stableJson({
    topic: left.topic,
    score: left.score,
    totalQuestions: left.totalQuestions,
    answers: left.answers,
    partialCreditPoints: left.partialCreditPoints,
    partialCredits: left.partialCredits,
    timing: left.timing,
    flaggedQuestionIds: left.flaggedQuestionIds,
    pendingGradeQuestionIds: left.pendingGradeQuestionIds,
    skippedQuestionIds: left.skippedQuestionIds,
    sessionId: left.sessionId,
  }) === stableJson({
    topic: right.topic,
    score: right.score,
    totalQuestions: right.totalQuestions,
    answers: right.answers,
    partialCreditPoints: right.partialCreditPoints,
    partialCredits: right.partialCredits,
    timing: right.timing,
    flaggedQuestionIds: right.flaggedQuestionIds,
    pendingGradeQuestionIds: right.pendingGradeQuestionIds,
    skippedQuestionIds: right.skippedQuestionIds,
    sessionId: right.sessionId,
  });
}

/** Check creation time may be regenerated by a replay; its learner response and grade may not. */
function sameQuestionCheckEvidence(left: LearnerQuestionCheck, right: LearnerQuestionCheck): boolean {
  return left.id === right.id && stableJson({
    topic: left.topic,
    question: left.question,
    answer: left.answer,
    grading: left.grading,
    score: left.score,
    misconception: left.misconception,
    sessionId: left.sessionId,
  }) === stableJson({
    topic: right.topic,
    question: right.question,
    answer: right.answer,
    grading: right.grading,
    score: right.score,
    misconception: right.misconception,
    sessionId: right.sessionId,
  });
}

/** Updates exactly one durable goal step. Missing goals or steps fail without a fallback write. */
export function updateGoalStep(
  data: PortableLearnerData,
  goalId: string,
  stepId: string,
  status: GoalStepStatus,
  nowIso: string,
): PortableLearnerData {
  requireValidSource(data);
  const goal = data.goals.find((candidate) => candidate.id === goalId);
  if (!goal) throw new Error(`Goal ${goalId} does not exist.`);
  if (!goal.steps.some((step) => step.id === stepId)) throw new Error(`Step ${stepId} does not exist in goal ${goalId}.`);
  return requireValidResult({
    ...data,
    generatedAt: nowIso,
    goals: data.goals.map((candidate) => candidate.id !== goalId ? candidate : {
      ...candidate,
      updatedAt: nowIso,
      steps: candidate.steps.map((step) => step.id === stepId ? { ...step, status } : step),
    }),
  });
}

/** Atomically prepares the exact deck replacement and immutable review event for a repository transaction. */
export function recordCardReview(
  data: PortableLearnerData,
  deckId: string,
  cardId: string,
  rating: SrsRating,
  reviewId: string,
  nowIso: string,
  sessionId?: string,
): CardReviewMutationResult {
  requireValidSource(data);
  if (data.cardReviews.some((review) => review.id === reviewId)) {
    throw new Error(`Review ${reviewId} already exists.`);
  }
  const deck = data.decks.find((candidate) => candidate.id === deckId);
  if (!deck) throw new Error(`Deck ${deckId} does not exist.`);
  if (!deck.cards.some((card) => card.id === cardId)) throw new Error(`Card ${cardId} does not exist in deck ${deckId}.`);
  const applied = applyPortableCardReview(deck, cardId, rating, {
    reviewId,
    createdAt: nowIso,
    ...(sessionId ? { sessionId } : {}),
  });
  const next = requireValidResult({
    ...data,
    generatedAt: nowIso,
    decks: data.decks.map((candidate) => candidate.id === deckId ? applied.deck : candidate),
    cardReviews: [...data.cardReviews, applied.review],
  });
  return { data: next, review: applied.review };
}

/**
 * Replaces a learner's choice for one semantic target. An existing target keeps
 * its durable id; caller-supplied ids are only used when creating a new choice.
 */
export function setStudyPriority(
  data: PortableLearnerData,
  targetType: StudyPriorityTargetType,
  targetId: string,
  priority: StudyPriority,
  recordId: string,
  nowIso: string,
): StudyPriorityMutationResult {
  requireValidSource(data);
  const current = data.studyPriorities.find((candidate) =>
    candidate.targetType === targetType && candidate.targetId === targetId);
  const record = createStudyPriority({
    id: current?.id ?? recordId,
    targetType,
    targetId,
    priority,
    updatedAt: nowIso,
  });
  const next = requireValidResult({
    ...data,
    generatedAt: nowIso,
    studyPriorities: current
      ? data.studyPriorities.map((candidate) => candidate.id === current.id ? record : candidate)
      : [...data.studyPriorities, record],
  });
  return { data: next, record };
}

/**
 * Inserts a completed goal card exactly once. A retry observes the learner's
 * existing progress; it cannot replace it with a stale card payload.
 */
export function ensureLearnerGoal(
  data: PortableLearnerData,
  goal: LearnerGoal,
  nowIso: string,
): PortableLearnerData {
  requireValidSource(data);
  requireMutationTimestamp(nowIso);
  if (!validateLearnerGoal(goal)) throw new Error("Cannot insert an invalid learner goal.");
  const existing = data.goals.find((candidate) => candidate.id === goal.id);
  if (existing) {
    if (!sameGoalSource(existing, goal)) throw new Error(`Learner goal identity conflict for ${goal.id}.`);
    return data;
  }
  return requireValidResult({ ...data, generatedAt: nowIso, goals: [...data.goals, structuredClone(goal)] });
}

/** Appends one quiz result exactly once, preserving a retry's original evidence. */
export function appendQuizResult(
  data: PortableLearnerData,
  result: LearnerQuizResult,
  nowIso: string,
): PortableLearnerData {
  requireValidSource(data);
  requireMutationTimestamp(nowIso);
  if (!validateLearnerQuizResult(result)) throw new Error("Cannot append an invalid quiz result.");
  const existing = data.quizResults.find((candidate) => candidate.id === result.id);
  if (existing) {
    if (!sameQuizEvidence(existing, result)) throw new Error(`Quiz result identity conflict for ${result.id}.`);
    return data;
  }
  return requireValidResult({ ...data, generatedAt: nowIso, quizResults: [...data.quizResults, structuredClone(result)] });
}

/**
 * Atomically appends a card's question-check batch. Any malformed or
 * conflicting item aborts the entire batch before a snapshot is returned.
 */
export function appendQuestionChecks(
  data: PortableLearnerData,
  checks: readonly LearnerQuestionCheck[],
  nowIso: string,
): PortableLearnerData {
  requireValidSource(data);
  requireMutationTimestamp(nowIso);
  const known = new Map(data.questionChecks.map((check) => [check.id, check]));
  const additions: LearnerQuestionCheck[] = [];
  const incoming = new Map<string, LearnerQuestionCheck>();
  for (const check of checks) {
    if (!validateLearnerQuestionCheck(check)) throw new Error("Cannot append an invalid question check.");
    const priorIncoming = incoming.get(check.id);
    if (priorIncoming && !sameQuestionCheckEvidence(priorIncoming, check)) {
      throw new Error(`Question check identity conflict for ${check.id}.`);
    }
    if (priorIncoming) continue;
    incoming.set(check.id, check);
    const existing = known.get(check.id);
    if (existing) {
      if (!sameQuestionCheckEvidence(existing, check)) throw new Error(`Question check identity conflict for ${check.id}.`);
      continue;
    }
    additions.push(check);
  }
  if (additions.length === 0) return data;
  return requireValidResult({
    ...data,
    generatedAt: nowIso,
    questionChecks: [...data.questionChecks, ...additions.map((check) => structuredClone(check))],
  });
}
